name: CI/CD

on:
  push:
    branches:
      - ci-refactoring
      - mainnet
      - testnet
      - dev
  pull_request:

jobs:
  build_base:
    name: Build & Test
    if: github.event_name != 'pull_request' || github.event.pull_request.head.ref != 'weblate-tr'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      # - name: Update service-worker.js version with commit hash
      #   if: github.ref == 'refs/heads/mainnet' || github.ref == 'refs/heads/testnet'
      #   run: |
      #     sed -i "s/^const VERSION = '.*';/const VERSION = '${GITHUB_SHA}';/" ./apps/web/public/service-worker.js

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PAT }}

      - name: Build Docker image for base
        uses: docker/build-push-action@v6
        with:
          push: ${{ (github.event_name == 'push') && (github.ref == 'refs/heads/mainnet' || github.ref == 'refs/heads/testnet') }}
          file: ./docker/Dockerfile.base
          context: .
          tags: docker.io/pokerdan1/bitcoin-learning-management-system:base-${{ github.sha }}
          cache-from: type=gha,scope=global
          cache-to: type=gha,mode=max,scope=global

  build_api:
    name: Build API
    if: (github.event_name == 'push') && (github.ref == 'refs/heads/mainnet' || github.ref == 'refs/heads/testnet')
    runs-on: ubuntu-latest
    needs: build_base
    env:
      image: docker.io/pokerdan1/bitcoin-learning-management-system
      base: docker.io/pokerdan1/bitcoin-learning-management-system:base-${{ github.sha }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Update service-worker.js version with commit hash
        if: github.ref == 'refs/heads/mainnet' || github.ref == 'refs/heads/testnet'
        run: |
          sed -i "s/^const VERSION = '.*';/const VERSION = '${GITHUB_SHA}';/" ./apps/web/public/service-worker.js

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PAT }}

      - name: Set Docker image metadata
        uses: docker/metadata-action@v5
        id: meta
        with:
          images: ${{ env.image }}
          flavor: |
            suffix=-api
          tags: |
            type=schedule
            type=ref,event=branch
            type=ref,event=tag
            type=sha,prefix=sha-

      - name: Build and push Docker image for api
        uses: docker/build-push-action@v6
        with:
          push: ${{ (github.event_name == 'push') && (github.ref == 'refs/heads/mainnet' || github.ref == 'refs/heads/testnet') }}
          file: ./apps/api/docker/Dockerfile
          context: .
          tags: ${{ steps.meta.outputs.tags }}
          cache-from: type=gha,scope=global
          cache-to: type=gha,mode=max,scope=global
          build-args:
            BASE_IMAGE=${{ env.base }}

  build_web:
    name: Build Web
    if: (github.event_name == 'push') && (github.ref == 'refs/heads/mainnet' || github.ref == 'refs/heads/testnet')
    runs-on: ubuntu-latest
    needs: build_base
    env:
      image: docker.io/pokerdan1/bitcoin-learning-management-system
      base: docker.io/pokerdan1/bitcoin-learning-management-system:base-${{ github.sha }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PAT }}

      - name: Set Docker image metadata for web
        uses: docker/metadata-action@v5
        id: meta
        with:
          images: ${{ env.image }}
          flavor: |
            suffix=-web
          tags: |
            type=schedule
            type=ref,event=branch
            type=ref,event=tag
            type=sha,prefix=sha-

      - name: Build and push Docker image for web
        uses: docker/build-push-action@v6
        with:
          push: ${{ (github.event_name == 'push') && (github.ref == 'refs/heads/mainnet' || github.ref == 'refs/heads/testnet') }}
          file: ./apps/web/docker/Dockerfile
          context: .
          tags: ${{ steps.meta.outputs.tags }}
          cache-from: type=gha,scope=global
          cache-to: type=gha,mode=max,scope=global
          build-args:
            BASE_IMAGE=${{ env.base }}

  build_contribute:
    name: Build contribute
    if: (github.event_name == 'push') && (github.ref == 'refs/heads/mainnet' || github.ref == 'refs/heads/testnet')
    runs-on: ubuntu-latest
    needs: build_base
    env:
      image: docker.io/pokerdan1/bitcoin-learning-management-system
      base: docker.io/pokerdan1/bitcoin-learning-management-system:base-${{ github.sha }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PAT }}

      - name: Set Docker image metadata for contribute
        uses: docker/metadata-action@v5
        id: meta
        with:
          images: ${{ env.image }}
          flavor: |
            suffix=-contribute
          tags: |
            type=schedule
            type=ref,event=branch
            type=ref,event=tag
            type=sha,prefix=sha-

      - name: Build and push Docker image for contribute
        uses: docker/build-push-action@v6
        with:
          push: ${{ (github.event_name == 'push') && (github.ref == 'refs/heads/mainnet' || github.ref == 'refs/heads/testnet') }}
          file: ./apps/contribute/docker/Dockerfile
          context: .
          tags: ${{ steps.meta.outputs.tags }}
          cache-from: type=gha,scope=global
          cache-to: type=gha,mode=max,scope=global
          build-args:
            BASE_IMAGE=${{ env.base }}

  build_design_system:
    name: Build Design System
    if: (github.event_name == 'push') && (github.ref == 'refs/heads/mainnet' || github.ref == 'refs/heads/testnet')
    runs-on: ubuntu-latest
    needs: build_base
    env:
      image: docker.io/pokerdan1/bitcoin-learning-management-system
      base: docker.io/pokerdan1/bitcoin-learning-management-system:base-${{ github.sha }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PAT }}

      - name: Set Docker image metadata for design system
        uses: docker/metadata-action@v5
        id: meta
        with:
          images: ${{ env.image }}
          flavor: |
            suffix=-design-system
          tags: |
            type=schedule
            type=ref,event=branch
            type=ref,event=tag
            type=sha,prefix=sha-

      - name: Build and push Docker image for design system
        uses: docker/build-push-action@v6
        with:
          push: ${{ (github.event_name == 'push') && (github.ref == 'refs/heads/mainnet' || github.ref == 'refs/heads/testnet') }}
          file: ./packages/ui/docker/Dockerfile
          context: .
          tags: ${{ steps.meta.outputs.tags }}
          cache-from: type=gha,scope=global
          cache-to: type=gha,mode=max,scope=global
          build-args:
            BASE_IMAGE=${{ env.base }}
